# test_config.yml
# HCRBackup test config

# General Options
database-name: DATABASE-NAME
vault-name: VAULT-NAME
aws-id: 000000000000
aws-profile: AWS-PROFILE
command: backup # [ backup | new-vault ]

# backup options
no-backup: false
no-prune: false
dummy-upload: false

# new-vault options
new-vault-name: NEW-VAULT-NAME

# Advanced Options
debug: false
logging-dir: /home/USERNAME
backup-directory: /path/to/dir
